<?xml version="1.0"?>
<robot name="excavator" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="itom" value="0.0254" /> <!-- Inches to meters conversion -->

  <xacro:property name="base_width" value="${29*itom}"/>
  <xacro:property name="base_length" value="${58*itom}"/> <!-- Max val: 50" bare minimum -->
  <xacro:property name="base_height" value="${2*itom}"/> <!-- BS'd this number, total random guess -->

  <xacro:property name="wheel_radius" value="${16*itom}"/>
  <xacro:property name="wheel_width" value="${6*itom}"/>

  <xacro:property name="mass" value="5000" />

  <xacro:include filename="$(find exc_description)/urdf/exc.gazebo" />

  <xacro:macro name="wheel" params="name fb lr">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin rpy="${pi/2} 0 0" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin rpy="${pi/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 ${wheel_width/2} 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (wheel_radius*wheel_radius*pi*2)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (wheel_radius*wheel_radius*pi*2)}" iyz="0.0" izz="${mass / 12.0 * (wheel_radius*wheel_radius*pi*2)}"/> <!-- Temporary inertia: change -->
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/><!--rpy="0 0 ${pi/2}"-->
      <origin xyz="${fb*base_length/2 - 8*fb*itom} ${lr*base_width/2 + lr*wheel_width} ${-base_height/2}"/>
      <axis xyz="0 1 0"/>
      <limit effort="10000000.0"  velocity="10000"/>
      <dynamics damping="0.7"/>
    </joint>
    <transmission name="${name}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="250"/>
      <inertia ixx="${mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (base_height*base_height + base_length*base_length*pi)}" iyz="0.0" izz="${mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
    </inertial>
  </link>

  <xacro:wheel name="wheel_fr" fb="1" lr="-1" />
  <xacro:wheel name="wheel_fl" fb="1" lr="1" />
  <xacro:wheel name="wheel_rr" fb="-1" lr="-1" />
  <xacro:wheel name="wheel_rl" fb="-1" lr="1" />

  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${1*itom} ${1*itom} ${1*itom}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${1*itom} ${1*itom} ${1*itom}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${base_length/2} 0 ${base_height}" />
    <parent link="base_link" />
    <child link="camera_link" />
  </joint>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/exc</robotNamespace>
    </plugin>
  </gazebo>

</robot>
